version: '3.1'

services:
  web:
    build: .
    command: yarn run dev
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
